name: "Terraform"

on:
  push: 
    branches: ["main"]
    
jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
          -var="aws_ecr_name=${{ secrets.AWS_ECR_NAME }}"
          -var="aws_region=${{ secrets.AWS_REGION_NAME }}"
          -var="lab_role=${{ secrets.AWS_ROLE_ARN }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  deploy-ecr-keycloak:
    name: Deploy AWS ECR
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      - name: Get timestamp
        id: get-timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_KEYCLOAK }}
          IMAGE_TAG: latest
        run: |
          cd container
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  infra-keycloak:
    name: "Terraform Apply Keycloak"
    runs-on: "ubuntu-latest"
    needs: deploy-ecr-keycloak
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Terraform ecr
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init ecs
        run: |
          cd ecs
          terraform init -backend-config='example.s3.tfbackend'

      - name: Terraform Plan ecs
        run: |
          cd ecs
          terraform plan

      - name: Terraform Apply ecs
        run: |
          cd ecs
          terraform apply -auto-approve
